#!/usr/bin/env python3
"""Generate deduplicated OpenClash classical rule providers from Loon rules."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RULESETS = {
    "direct": (ROOT / "direct.conf", "DIRECT"),
    "proxy": (ROOT / "proxy.conf", "PROXY"),
}


def parse_rules(path: Path, expected_policy: str) -> list[str]:
    rules: list[str] = []
    seen: set[str] = set()
    in_rule_section = False

    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            in_rule_section = line.casefold() == "[rule]"
            continue
        if not in_rule_section:
            continue

        parts = [part.strip() for part in line.split(",")]
        if len(parts) < 3:
            raise ValueError(f"{path.name}:{line_number}: invalid rule: {line}")

        policy = parts[2].upper()
        if policy != expected_policy:
            raise ValueError(
                f"{path.name}:{line_number}: expected {expected_policy}, found {parts[2]}"
            )

        rule = ",".join(parts[:2] + parts[3:])
        if rule not in seen:
            seen.add(rule)
            rules.append(rule)

    return rules


def render_yaml(source_name: str, rules: list[str]) -> str:
    lines = [
        "# Generated by scripts/generate_openclash.py; do not edit manually.",
        f"# Source: {source_name}",
        "payload:",
    ]
    lines.extend(f"  - {rule!r}" for rule in rules)
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated files are current without modifying them",
    )
    args = parser.parse_args()

    output_dir = ROOT / "openclash"
    changed: list[Path] = []

    for name, (source, expected_policy) in RULESETS.items():
        content = render_yaml(source.name, parse_rules(source, expected_policy))
        output = output_dir / f"{name}.yaml"
        current = output.read_text(encoding="utf-8") if output.exists() else None
        if current != content:
            changed.append(output)
            if not args.check:
                output.parent.mkdir(parents=True, exist_ok=True)
                output.write_text(content, encoding="utf-8")

    if args.check and changed:
        names = ", ".join(path.relative_to(ROOT).as_posix() for path in changed)
        raise SystemExit(f"Generated files are out of date: {names}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
